[tool.poetry]
name = "dw-events"
version = "0.0.0"
description = "Downwind Events"
authors = ["Guto Maia <guto@guto.net>"]

[tool.poetry.dependencies]
python = "^3.12"
dw-core = "0.0.0"
pydantic = "^2.11.4"
inject = "^5.2.1"

[tool.poetry.group.dev.dependencies]
dw-core = {path = "../dw-core", develop = true}
bandit = "^1.8.3"
git-changelog = "^2.5.3"
m2r = "^0.3.1"
pytest = "^8.3.5"
pytest-cov = "^6.1.1 "
pytest-watch = "^4.2.0"
sphinx-autodoc-typehints = "^3.2.0"
sphinx-multiversion = "^0.2.4"
sphinx-rtd-theme = "^3.0.2"
sphinxcontrib-plantuml = "^0.30"
ghp-import = "^2.1.0"
black = "^25.1.0"
prettier = "^0.0.7"
flake8 = "^7.2.0"
flake8-quotes = "^3.4.0"
isort = "^6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."ports"]
"test-notify" = "dw_events.notify:notify_send"
"tasker" = "dw_events.notify:Tasker"

[tool.poetry.plugins."argument_resolvers"]
"dw-events-deferred-emitter" = "dw_events.resolver:DeferredEmitterArgumentResolver"
